In [1]:
import numpy as np

In [2]:
array_n1 = np.array([1,2,3,4])

In [3]:
array_n1

array([1, 2, 3, 4])

In [4]:
print(array_n1)

[1 2 3 4]


In [5]:
print(type(array_n1))

<class 'numpy.ndarray'>


In [6]:
print(type(array_n1[0]))

<class 'numpy.int64'>


In [8]:
array_n2 = np.array([4,5,6,2],dtype=np.int8)
print(array_n2)
print(type(array_n2))
print(type(array_n2[0]))


[4 5 6 2]
<class 'numpy.ndarray'>
<class 'numpy.int8'>


In [9]:
array_n3 = np.array([25.2, 44.1, 23.0])
print(array_n3)
print(type(array_n3))
print(type(array_n3[0]))

[25.2 44.1 23. ]
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [ ]:
array_n4 = np.array([1.32, 2.24, 0.96],dtype=np.float32)
print(array_n4)
print(type(array_n4))
print(type(array_n4[0]))

[1.32 2.24 0.96]
<class 'numpy.ndarray'>
<class 'numpy.float32'>


In [14]:
print(np.arange(0,5))

[0 1 2 3 4]


In [15]:
print(np.arange(1,9,2))

[1 3 5 7]


In [17]:
np_arange = np.arange(2,22,3)
print(np_arange)
print(type(np_arange))

[ 2  5  8 11 14 17 20]
<class 'numpy.ndarray'>


In [18]:
np_linspace = np.linspace(1,10,1000)
print(np_linspace)
print(type(np_linspace))

[ 1.          1.00900901  1.01801802  1.02702703  1.03603604  1.04504505
  1.05405405  1.06306306  1.07207207  1.08108108  1.09009009  1.0990991
  1.10810811  1.11711712  1.12612613  1.13513514  1.14414414  1.15315315
  1.16216216  1.17117117  1.18018018  1.18918919  1.1981982   1.20720721
  1.21621622  1.22522523  1.23423423  1.24324324  1.25225225  1.26126126
  1.27027027  1.27927928  1.28828829  1.2972973   1.30630631  1.31531532
  1.32432432  1.33333333  1.34234234  1.35135135  1.36036036  1.36936937
  1.37837838  1.38738739  1.3963964   1.40540541  1.41441441  1.42342342
  1.43243243  1.44144144  1.45045045  1.45945946  1.46846847  1.47747748
  1.48648649  1.4954955   1.5045045   1.51351351  1.52252252  1.53153153
  1.54054054  1.54954955  1.55855856  1.56756757  1.57657658  1.58558559
  1.59459459  1.6036036   1.61261261  1.62162162  1.63063063  1.63963964
  1.64864865  1.65765766  1.66666667  1.67567568  1.68468468  1.69369369
  1.7027027   1.71171171  1.72072072  1.72972973  1.

In [19]:
np_linspace = np.linspace(1,100,4)
print(np_linspace)
print(type(np_linspace))

[  1.  34.  67. 100.]
<class 'numpy.ndarray'>


In [20]:
for i in np.linspace(1,10,10):
    print(i)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [21]:
np_zeroes = np.zeros(5)
print(np_zeroes)

[0. 0. 0. 0. 0.]


In [22]:
np_zeroes.ndim

1

In [25]:
np_zeroes_2d = np.zeros((5,5))
print(np_zeroes_2d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
np_zeroes_2d.ndim

2

In [27]:
np_zeros_3d = np.zeros((5,5,5))
print(np_zeros_3d)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [28]:
np_zeros_3d.ndim

3

In [29]:
import numpy as np

In [31]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [33]:
np.zeros(5).ndim

1

In [35]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [37]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
np.zeros((5,5)).ndim

2

In [39]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
np.ones((5,5)).ndim

2

In [41]:
np.ones((5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [42]:
type(np.ones((1,1)))

numpy.ndarray

In [43]:
np.full((5,5),0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [44]:
np.full((5,5),100)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [45]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [46]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
np.eye(3,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [48]:
np.eye(6,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [49]:
np.eye(6,6,3)

array([[0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [50]:
np.eye(6,6,-3)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [51]:
a = np.full((5,5),0)

In [52]:
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [53]:
print(type(a))

<class 'numpy.ndarray'>


In [54]:
np.empty((5,5))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.20161933e-306, 1.89146896e-307],
       [7.56571288e-307, 4.00544531e-307, 1.11261095e-306,
        3.56043054e-307, 1.37961641e-306],
       [2.22518251e-306, 1.33511969e-306, 6.23037657e-307,
        9.34609790e-307, 8.45593934e-307],
       [9.34600963e-307, 1.42418987e-306, 1.60219035e-306,
        8.06635109e-308, 1.39071360e-307],
       [8.90060780e-307, 8.06638505e-308, 1.37961506e-306,
        7.23168527e-308, 2.56765117e-312]])

In [55]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [56]:
np.empty((5,5),dtype=np.int16)

array([[    0,     0,    63,    92,  2208],
       [    0,     0,     0,     0,     0],
       [    0,     0, -2320,  8409,   515],
       [    0,     0,     0,     0,     0],
       [  257,     1,    68,    97,   116]], dtype=int16)

In [57]:
np.random.rand(5,5)

array([[0.35340535, 0.81228517, 0.52801813, 0.93955601, 0.02763209],
       [0.01864511, 0.40611678, 0.21818665, 0.58344871, 0.72527291],
       [0.10737094, 0.3597482 , 0.78232947, 0.93074145, 0.11090152],
       [0.9567576 , 0.25975595, 0.73675877, 0.00262047, 0.65725919],
       [0.04174903, 0.36107653, 0.06321206, 0.92557073, 0.61310758]])

In [59]:
np.random.randint(1,10,10)

array([6, 4, 3, 9, 2, 2, 7, 4, 4, 8], dtype=int32)

In [60]:
np.random.randint(1,10,10)

array([4, 9, 8, 1, 9, 8, 5, 7, 3, 6], dtype=int32)

In [61]:
arr = np.array(([1,2,3],[4,5,6]))

In [62]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [63]:
arr.shape

(2, 3)

In [64]:
arr.ndim

2

In [66]:
arr.itemsize #size of bytes of each element

8

In [67]:
arr.nbytes #total number of bytes consumed by arry

48

In [68]:
arr = np.array(([1,2,3],[4,5,6]))

In [69]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [1]:
import numpy as np

In [2]:
arr = np.array([10,20,30,40,50,60])

In [3]:
arr

array([10, 20, 30, 40, 50, 60])

In [4]:
arr.ndim

1

In [5]:
print(arr[0])

10


In [6]:
print(arr[-1])

60


In [7]:
print(arr[1:4])

[20 30 40]


In [8]:
arr

array([10, 20, 30, 40, 50, 60])

In [9]:
print(arr)

[10 20 30 40 50 60]


In [10]:
print(arr[0:3])

[10 20 30]


In [11]:
print(arr[:3])

[10 20 30]


In [12]:
print(arr[0:5:2])

[10 30 50]


In [13]:
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [14]:
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
print(mat[0,1])

2


In [16]:
print(mat[0,0])

1


In [17]:
print(mat[1,1])

5


In [18]:
print(mat[1])

[4 5 6]


In [20]:
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
print(mat[:,2])

[3 6 9]


In [22]:
print(mat[:,-1])

[3 6 9]


In [24]:
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
print(mat[0:2,:])

[[1 2 3]
 [4 5 6]]


In [26]:
print(mat[0:2,1:])

[[2 3]
 [5 6]]


In [27]:
arr_temp = np.array([1,2,3,4,5,6,7,8,9])

In [28]:
print(arr_temp[::-1])

[9 8 7 6 5 4 3 2 1]


In [29]:
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
print(mat[::-1])

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [31]:
print(mat[::-1,::-1])

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [32]:
arr = np.array([5,10,15,20,25])

In [33]:
print(arr)

[ 5 10 15 20 25]


In [34]:
arr

array([ 5, 10, 15, 20, 25])

In [35]:
arr>10

array([False, False,  True,  True,  True])

In [36]:
print(arr>10)

[False False  True  True  True]


In [37]:
arr[arr>10]

array([15, 20, 25])

In [38]:
indx = [1,3,4]
print(arr[indx])

[10 20 25]


In [39]:
arr[0] = 50
print(arr)

[50 10 15 20 25]


In [40]:
arr = np.array([10,20,25,30,35])

In [41]:
print(arr)

[10 20 25 30 35]


In [42]:
arr_1 = np.where(arr>20)

In [43]:
print(arr_1)

(array([2, 3, 4]),)


In [45]:
idx = np.where(arr>20)

In [46]:
print(idx)

(array([2, 3, 4]),)


In [47]:
print(arr[idx])

[25 30 35]


In [48]:
arr = np.array([1,2,3,4,5,6])

In [49]:
arr.shape

(6,)

In [50]:
rshape = arr.reshape(2,3)

In [51]:
print(rshape)

[[1 2 3]
 [4 5 6]]


In [52]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [53]:
rshape = arr.reshape(3,-1)

In [54]:
print(rshape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [55]:
rshape.shape

(3, 4)

In [56]:
a = np.array([[1,2],[3,4]])

In [57]:
a

array([[1, 2],
       [3, 4]])

In [58]:
b = a.flatten()

In [59]:
b

array([1, 2, 3, 4])

In [60]:
print(b)

[1 2 3 4]


In [61]:
ar = np.array([1,2,3,4])

In [63]:
ar.resize((2,3))

In [64]:
print(ar)

[[1 2 3]
 [4 0 0]]


In [65]:
ar = np.array([1,2,3,4])

In [66]:
ar.resize((2,1))

In [67]:
print(ar)

[[1]
 [2]]


In [70]:
arry2d = np.array([[2,18,19],[8,19,13]])

In [75]:
print(arry2d)
print(arry2d.shape)

[[ 2 18 19]
 [ 8 19 13]]
(2, 3)


In [73]:
arry2d_1 = np.array([[88,11,55],[99,66,77]])

In [76]:
print(arry2d_1)
print(arry2d_1.shape)

[[88 11 55]
 [99 66 77]]
(2, 3)


In [79]:
array3d = np.array([[[2,18,19],[8,19,13]],[[88,11,55],[99,66,77]]])
array3d.shape

(2, 2, 3)

In [80]:
a = np.array([[[1],[2],[3]]])

In [81]:
print(a)

[[[1]
  [2]
  [3]]]


In [82]:
a.shape

(1, 3, 1)

In [83]:
a = np.array([[1],[2],[3]])

In [84]:
print(a)

[[1]
 [2]
 [3]]


In [85]:
a.shape

(3, 1)

In [86]:
a = np.array([[[1],[2],[3]],[[1],[2],[3]]])

In [87]:
print(a.shape)

(2, 3, 1)


In [88]:
print(a)

[[[1]
  [2]
  [3]]

 [[1]
  [2]
  [3]]]


In [89]:
a = np.array([[[1],[2],[3]]])

In [90]:
a.shape

(1, 3, 1)

In [92]:
b = a.squeeze()

In [93]:
print(b)

[1 2 3]


In [94]:
print(b.shape)

(3,)


In [95]:
b = np.array([b])

In [96]:
print(b)

[[1 2 3]]


In [97]:
print(b.shape)

(1, 3)


In [100]:
a = np.array([[[1],[2],[3]],[[1],[2],[3]]])

In [101]:
print(a.shape)

(2, 3, 1)


In [102]:
b = a.squeeze()

In [103]:
print(b)

[[1 2 3]
 [1 2 3]]


In [104]:
print(b.shape)

(2, 3)


In [105]:
ar = np.array([[1,2,3],[1,2,3],[1,2,3]])

In [106]:
ar.shape

(3, 3)

In [109]:
print(np.sum(ar, axis=0))#row wise

[3 6 9]


In [110]:
print(np.sum(ar, axis=1))

[6 6 6]


In [1]:
a = [1,2,3]
b = [4,5,6]

In [2]:
a + b

[1, 2, 3, 4, 5, 6]

In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [5]:
a + b

array([5, 7, 9])

In [6]:
print(a - b)
print(a*b)
print(a/b)

[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [7]:
print(a > b)
print(a < b)
print(a == b)

[False False False]
[ True  True  True]
[False False False]


In [8]:
print(type(a > b))

<class 'numpy.ndarray'>


In [9]:
ans = a > b

In [10]:
print(ans)

[False False False]


In [11]:
print(type(ans[0]))

<class 'numpy.bool'>


In [14]:
x = np.array([True, False, True])
y = np.array([False, False, True])

print(np.logical_and(x,y))
print(np.logical_or(x,y))
print(np.logical_not(x))
print(np.logical_not(y))

[False False  True]
[ True False  True]
[False  True False]
[ True  True False]


In [15]:
a = np.array([1,2,3])
b = np.array([0,1,1])

print(np.bitwise_and(a,b))
print(np.bitwise_or(a,b))
print(np.bitwise_not(a))
print(np.bitwise_not(b))

[0 0 1]
[1 3 3]
[-2 -3 -4]
[-1 -2 -2]


In [16]:
#modulus and power
a = np.array([10,20,30])
b = np.array([3,7,4])
print(np.mod(a,b))

[1 6 2]


In [17]:
print(np.power(a,b))

[      1000 1280000000     810000]


In [ ]:
#scalar operations 
celcius = np.array([0, 10, 20, 30, 40])
print(celcius * 9 / 5 + 32) #broadcasting

[ 32.  50.  68.  86. 104.]


In [ ]:
celcius = [0, 10, 20, 30, 40]
print(celcius * 9/5 + 32 ) #In list the same operation with throw error

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [ ]:
#common maths operations
a = np.array([1, 2, 3, 4])

print(np.sqrt(a))
print(np.exp(a))# e^1, e^2, e^3, e^4 where e = 2.718
print(np.log(a))
print(np.sin(a))

[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [27]:
#Aggregation Functions
a = np.array([[1,2,3],
               [4,5,6]])

In [25]:
a.ndim

2

In [28]:
print(np.sum(a))

21


In [29]:
print(np.sum(a, axis =0))

[5 7 9]


In [30]:
print(np.sum(a, axis = 1))

[ 6 15]


In [31]:
print(np.mean(a))

3.5


In [32]:
print(np.std(a))

1.707825127659933


In [33]:
print(np.min(a))

1


In [34]:
print(np.max(a))

6


In [36]:
#matrix operation
#element wise multiplication
units = np.array([100, 200, 150])
profit = np.array([10, 20, 30])
units*profit

array([1000, 4000, 4500])

In [42]:
#Dot Product
house = np.array([[1200, 3, 1],
                  [1200, 3, 0],
                  [1000, 3, 0],
                  [1000, 1, 1]])
w = np.array([200, 10000, 50000])

In [43]:
print(np.dot(house, w))

[320000 270000 230000 260000]


In [44]:
house * w

array([[240000,  30000,  50000],
       [240000,  30000,      0],
       [200000,  30000,      0],
       [200000,  10000,  50000]])

In [45]:
print(np.sum(house*w, axis = 1))

[320000 270000 230000 260000]


In [46]:
A = np.array([[1,2,3,4],[1,2,3,4]])
B = np.array([[1,2,3,4],[1,2,3,4]])
print(A.shape)
print(B.shape)

(2, 4)
(2, 4)


In [ ]:
np.dot(A,B)#This statement will throw error

ValueError: shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)

In [48]:
np.dot(A,B.T)

array([[30, 30],
       [30, 30]])

In [50]:
print(A @ B.T)#Another way of performing dot product

[[30 30]
 [30 30]]


In [51]:
a = np.array([1,2,3])
b = np.array([[10],[20]])

In [52]:
print(a.shape)

(3,)


In [53]:
print(b.shape)

(2, 1)


In [ ]:
a + b
# due to broadcasting internal shapes are changed as below
#a --(2,3) -->[[1,2,3],[1,2,3]]
#b --(2,3) -->[[10, 10, 10],[20, 20, 20]]

array([[11, 12, 13],
       [21, 22, 23]])

In [55]:
a = [1,2,3,4]
a_npy = np.array(a)


In [61]:
print(a_npy, a_npy.dtype, type(a))

[1 2 3 4] int64 <class 'list'>


In [57]:
b = [[1,2],[3,4]]
b_npy = np.array(b)

In [62]:
print(b_npy, b_npy.dtype, type(b))

[[1 2]
 [3 4]] int64 <class 'list'>


In [59]:
c = (1,2,3,4)
c_npy = np.array(c)

In [63]:
print(c_npy, c_npy.dtype, type(c))

[1 2 3 4] int64 <class 'tuple'>


In [ ]:
#vstack - verticle stack
a = np.array([[1,2]])
b = np.array([[3,4]])

In [65]:
a.shape
b.shape

(1, 2)

In [67]:
print(np.vstack((a,b)))

[[1 2]
 [3 4]]


In [68]:
print(np.vstack((b,a)))

[[3 4]
 [1 2]]


In [ ]:
#hstack - horizontal stack
print(np.hstack((a,b)))

[[1 2 3 4]]


In [70]:
print(np.hstack((b,a)))

[[3 4 1 2]]


In [72]:
#np.char.<function_name>()
#1. np.char.add()

a = np.array(["hello","world"])
b = np.array(["_user","_123"])
print(np.char.add(a,b))

['hello_user' 'world_123']


In [74]:
#2. np.char.multiply()
print(np.char.multiply(a,2))

['hellohello' 'worldworld']


In [76]:
#3. np.char.upper() / lower() /capitalize()
a = np.array(["hello","WORLD"])
print(np.char.lower(a))
print(np.char.upper(a))
print(np.char.capitalize(a))

['hello' 'world']
['HELLO' 'WORLD']
['Hello' 'World']


In [77]:
#4. np.char.center()
print(np.char.center(a,10,fillchar='*'))

['**hello***' '**WORLD***']


In [78]:
#5. np.char.replace()
a = np.array(["machine_learning", "data_science"])
print(np.char.replace(a,'_',' '))

['machine learning' 'data science']


In [79]:
#6. np.char.split()
print(np.char.split(a, sep='_'))

[list(['machine', 'learning']) list(['data', 'science'])]


In [81]:
print(a)

['machine_learning' 'data_science']


In [84]:
#7 np.char.find() / np.char.count()
print(np.char.find(a,'learn'))
print(np.char.count(a,'a'))
print(np.char.count(a,'data'))

[ 8 -1]
[2 2]
[0 1]


In [85]:
#Statistical Function
data = np.array([1,2,3,4,5,6])
print("Mean: ",np.mean(data))

Mean:  3.5


In [86]:
print("Median: ",np.median(data))

Median:  3.5


In [87]:
print("Standard Deviation: ", np.std(data))

Standard Deviation:  1.707825127659933


In [88]:
print("Variance: ", np.var(data))

Variance:  2.9166666666666665


In [89]:
print("Min: ", np.min(data))

Min:  1


In [90]:
print("Max: ", np.max(data))

Max:  6


In [91]:
print("Argmin: ", np.argmin(data))
print("Argmax: ", np.argmax(data))

Argmin:  0
Argmax:  5


In [92]:
matrix = np.array([[1,2,3],
                   [4,5,6]])

In [93]:
matrix.shape

(2, 3)

In [94]:
matrix.ndim

2

In [97]:
print(np.mean(matrix, axis=0))
print(np.mean(matrix, axis=1))

[2.5 3.5 4.5]
[2. 5.]


In [ ]:
data = np.array([1,3,5,7,9])
print(np.percentile(data, 50))#range 1 to 100
print(np.quantile(data, 0.9))#range 0 to 1  

5.0
8.2


In [108]:
#sort, search and counting functions
arr = np.array([3, 6, 1, 1, 1, 1, 1, 8, 2, 5, 6])
print("Sorted: ", np.sort(arr))
print("Sorted Indices: ", np.argsort(arr))
print("Insert 4 position: ", np.searchsorted(np.sort(arr),4))
print("Unique Elements: ", np.unique(arr))

#min = 1
#max = 8
#creates an array from 0 to max element
#0,1,2,3,4,5,6,7,8 = len(9)
print("Count of each element: ", np.bincount(arr))

Sorted:  [1 1 1 1 1 2 3 5 6 6 8]
Sorted Indices:  [ 3  2  5  4  6  8  0  9 10  1  7]
Insert 4 position:  7
Unique Elements:  [1 2 3 5 6 8]
Count of each element:  [0 5 1 1 0 1 2 0 1]


In [109]:
arr = np.array([1,2,3,4])
for elements in arr:
    print(elements)

1
2
3
4


In [110]:
arr_2d = np.array([[1,2],[3,4]])
for elements in arr_2d:
    print(elements)

[1 2]
[3 4]


In [112]:
arr = np.arange(8).reshape(2,2,2)
print(arr)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [113]:
for elements in np.nditer(arr):
    print(elements)

0
1
2
3
4
5
6
7


In [114]:
a = np.array([1, 2, 3])
b = a
b[0] = 100

In [115]:
print(b)

[100   2   3]


In [116]:
print(a)

[100   2   3]


In [117]:
a = np.array([1,2,3])

In [118]:
b = a.copy()

In [119]:
b[0] = 100

In [120]:
print(b)
print(a)

[100   2   3]
[1 2 3]


In [121]:
a = np.array([1,2,3])
b = a.view()
c = a.copy()

In [122]:
b[0] = 10

In [123]:
print(b)

[10  2  3]


In [124]:
print(a)

[10  2  3]


In [125]:
c[0] = 20

In [126]:
print(a)
print(c)

[10  2  3]
[20  2  3]


In [131]:
a = np.arange(4)
b = a[1:4].view()
print(np.shares_memory(a,b))

True


In [132]:
print(id(a))
print(id(b))

2660729667472
2660729848240


In [128]:
a = np.arange(4)
b = a[1:4].copy()
print(np.shares_memory(a,b))

False


In [ ]:
print(array)